version: '2'
services:

  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:1.19.1
    networks:
      - color-nw
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /etc/nginx/certs

  nginx-proxy-gen:
    container_name: nginx-proxy-gen
    image: jwilder/docker-gen:0.7.0
    networks:
      - color-nw
    volumes_from:
      - nginx-proxy
    volumes:
      - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - nginx-proxy
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  nginx-letsencrypt:
    container_name: nginx-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.13
    networks:
      - color-nw
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
      - nginx-proxy-gen
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-proxy-gen
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
      - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory
      # - ACME_CA_URI=https://acme-v02.api.letsencrypt.org/directory

  postgres:
    container_name: postgres
    image: postgres:12.4
    networks:
      - color-nw
    depends_on:
      - nginx-proxy
      - nginx-proxy-gen
      - nginx-letsencrypt
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backups:/home/backups
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  play-backend:
    container_name: play-backend
    image: 453228891956.dkr.ecr.us-west-2.amazonaws.com/colorcontroversy-backend:2021-11-27.1
    command: sbt run
    networks:
      - color-nw
    depends_on:
      - nginx-proxy
      - nginx-proxy-gen
      - nginx-letsencrypt
      - postgres
    volumes:
      - ./play-backend:/root/app
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  react-frontend:
    container_name: react-frontend
    image: 453228891956.dkr.ecr.us-west-2.amazonaws.com/colorcontroversy-frontend:2022-03-06.1
    networks:
      - color-nw
    stdin_open: true
    tty: true
    depends_on:
    - nginx-proxy
    - nginx-proxy-gen
    - nginx-letsencrypt
    - postgres
    - play-backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}

volumes:
  postgres-data:

networks:
  color-nw:
