version: "2"
services:

  db:
    container_name: postgres
    image: postgres:12.3 
    networks:
      - color-nw
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy:latest
    networks:
      - color-nw
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-letsencrypt:
    container_name: nginx-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.13
    networks:
      - color-nw
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
      - ACME_CA_URI=${ACME_CA_URI}

  nginx:
    container_name: nginx
    image: nginx:1.19.1
    networks:
      - color-nw
    depends_on:
      - nginx-proxy
      - nginx-letsencrypt
    environment:
      - VIRTUAL_HOST=${HOSTNAME}
      - LETSENCRYPT_HOST=${HOSTNAME}


volumes:
  db-data:

networks:
  color-nw:

