version: '2'
services:

  nginx:
    container_name: nginx
    image: nginx:1.19.1
    networks:
      - color-nw
    depends_on:
      - react-frontend
      - play-backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  postgres:
    container_name: postgres
    image: postgres:12.4
    networks:
      - color-nw
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  play-backend:
    container_name: play-backend
    build:
      context: ./play-backend
      dockerfile: Dockerfile
    networks:
      - color-nw
    depends_on:
      - postgres
    volumes:
      - ./play-backend:/root/app
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  react-frontend:
    container_name: react-frontend
    build:
      context: ./react-frontend
      dockerfile: Dockerfile.dev
    networks:
      - color-nw
    stdin_open: true
    tty: true
    depends_on:
    - postgres
    - play-backend
    volumes:
      - ./react-frontend/tsconfig.json:/app/tsconfig.json
      - ./react-frontend/src:/app/src
      - ./react-frontend/public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres-data:

networks:
  color-nw:
