# pull official base image
FROM node:14.7.0-alpine3.12

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install
RUN npm install react-scripts@3.4.1 -g

# add app
COPY ./public ./public
COPY ./src ./src
COPY ./tsconfig.json ./tsconfig.json

# port
EXPOSE 3000

# start app
CMD ["npm", "start"]
