/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

export interface definitions {
  'models.Version': { playVersion: string }
  'models.Color': {
    hexColor: string
    color1: string
    color2: string
    nColor1: number
    nColor2: number
  }
}
